//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coffeeDate
    {
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string venue { get; set; }
        public char Username { get; internal set; }
        public string username { get; internal set; }
        public string password { get; internal set; }
    }
}
